services:
  app:
    build:
      context: .
    restart: always
    ports:
      - 55555:80
    links:
      - db

    env_file:
      - stack.env
    volumes:
      - images:/var/www/html/images
      # Commencez d'abord par lancer le conteneur sans activer cette option.
      # Lancez la procédure d'initialisation du Wiki, une fois cela fait,
      # déposez votre fichier LocalSettings.php dans le dossier "Eleutheria", et
      # activez cette option. Renseignez la variable d'environnement dans un
      # fichier ".env", lisible par Docker Compose.
      - $ELEUTHERIA_LOCAL_SETTINGS:/var/www/html/LocalSettings.php
  db:
    image: mariadb
    restart: always

    env_file:
      - stack.env
    environment:
      # @see https://phabricator.wikimedia.org/source/mediawiki/browse/master/includes/DefaultSettings.php
      MYSQL_DATABASE: eleutheria
      MYSQL_USER: app
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql

volumes:
  images:
  db:
