services:
  app:
    build:
      context: .
    restart: always
    ports:
      # Si non défini, port 55555
      - ${ELEUTHERIA_PORT:-55555}:80
    links:
      - db
    labels:
      - com.centurylinklabs.watchtower.enable=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:80"]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - images:/var/www/html/images
      # Commencez d'abord par lancer le conteneur sans activer cette option.
      # Lancez la procédure d'initialisation du Wiki, une fois cela fait,
      # déposez votre fichier LocalSettings.php dans le dossier "Eleutheria", et
      # activez cette option. Renseignez la variable d'environnement dans un
      # fichier ".env", lisible par Docker Compose.
      - $ELEUTHERIA_LOCAL_SETTINGS:/var/www/html/LocalSettings.php
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

    environment:
      # @see https://phabricator.wikimedia.org/source/mediawiki/browse/master/includes/DefaultSettings.php
      MYSQL_DATABASE: eleutheria
      MYSQL_USER: app
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql

volumes:
  images:
  db:
