services:
  app:
    build:
      context: .
    restart: always
    ports:
      # Si non défini, port 55555
      - ${ELEUTHERIA_PORT:-55555}:80
    links:
      - db
    labels:
      - com.centurylinklabs.watchtower.enable=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:80"]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - images:/var/www/html/images
      # Commencez d'abord par lancer le conteneur sans activer cette option.
      # Lancez la procédure d'initialisation du Wiki, une fois cela fait,
      # déposez votre fichier LocalSettings.php dans le dossier "Eleutheria", et
      # activez cette option. Renseignez la variable d'environnement dans un
      # fichier ".env", lisible par Docker Compose.
      - $ELEUTHERIA_LOCAL_SETTINGS:/var/www/html/LocalSettings.php
    depends_on:
      db:
        condition: service_healthy

    networks:
      - db

  db:
    image: mariadb
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 3s
      start_interval: 2s
      interval: 10s
      timeout: 5s
      retries: 5

    environment:
      # @see https://phabricator.wikimedia.org/source/mediawiki/browse/master/includes/DefaultSettings.php
      MYSQL_DATABASE: eleutheria
      MYSQL_USER: app
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"

    networks:
      - db

  loki:
    image: grafana/loki:3.4
    command: -config.file=/etc/loki/local-config.yaml
    environment:
      LOKI_USERNAME: $ELEUTHERIA_LOKI_USERNAME
      LOKI_PASSWORD: $ELEUTHERIA_LOKI_PASSWORD
    networks:
      - log-manager

  fluentd:
    image: grafana/fluent-plugin-loki:3.4
    command:
      - "fluentd"
      - "-v"
      - "-p"
      - "/fluentd/plugins"
    environment:
      LOKI_URL: http://loki:3100
      LOKI_USERNAME: $ELEUTHERIA_LOKI_USERNAME
      LOKI_PASSWORD: $ELEUTHERIA_LOKI_PASSWORD
    deploy:
      mode: global
    volumes:
      - 'logs:/fluentd/log'
      # Needed for journald log ingestion:
      # - /etc/machine-id:/etc/machine-id
      # - /dev/log:/dev/log
      # - /var/run/systemd/journal/:/var/run/systemd/journal/
    networks:
      - log-manager
    # logging:
    #   options:
    #     tag: infra.monitoring
    # ports:
    #   - '24224:24224/udp'
    #   - '24224:24224'

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - log-manager
      - db

networks:
  log-manager:
  db:

volumes:
  images:
  db:
  logs:
